### ISSUE TITLE
getting a warning when component is unmounted before the image was loaded

### ISSUE THREAD

**Issue by ofersarid** [oberonamsterdam/react-image-loading#1]
getting a warning when component is unmounted before the image was loaded

react-dom.development.js:506 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

need to cancel the request on componentWillUnount

**Comment by Richardvanwill** [comment]
@ofersarid thanks for reporting this. Fixed now in 0.2.1
